micronaut:
  application:
    name: keyManagerRest

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/rest-key
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    key-manager-grpc-channel:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 5

